### ISSUE TITLE
Graph on how Redux and Svelte is use?

### ISSUE THREAD

**Issue by proyb6** [lukechinworth/codenames#3]
Majority of us haven't touch Redux, it would be useful to explain and graph in this tutorial.

**Comment by lukechinworth** [comment]
Hey @proyb6 thanks for the interest. 

Svelte updates the dom when the data filling a component changes. This is done by calling `.set` on the component with a js object of the new data you want to pass to the component. If the component has children that depend on the data, Svelte updates the children based on the new data as well, similar to most js view libs. So the pattern with Redux is to update the top level component and have the changes trickle down to all the children. 

In my app, `Codenames` is the top level component. Notice [here](https://github.com/lukechinworth/codenames/blob/svelte/src/index.js#L15) I am calling `.set` on the `codenames` instance with the data return from `store.getState()`. Notice this function call is passed as a callback to the `.subscribe` method of the redux store. This callback is called every time an action is dispatched to the redux store, with `store.dispatch(action)`. You can see an example of dispatching an action to the store [here](https://github.com/lukechinworth/codenames/blob/svelte/src/components/Name.html#L22), where the name component is revealed on click. This action updates the state of the redux store, which calls the callback passed to `.subscribe` which calls `.set` on the top level component passing the new state of the redux store which updates the entire component tree.
